num_runs: 1
models: ["MLP","GP", "GP+Ph", "Ph"]
property_name: 'FE (Eth)'
run_name: gas_test
EI_reference: "max"
num_iter: 101
normalize_inputs: True
normalize_outputs: False
torch_seed: 0
use_existing_results: False
rebuild_all_runs_combined: True
